version: "3.8"
services:
  project:
    build: .
    ports:
      - "8080:8080"
    environment:
      -SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/spring?autoReconnect=true&useSSL=false
    depends_on:
      - mysqldb
 
  mysqldb:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=spring
    volumes:
      - spring:/data/db
volumes:
 spring: